### ISSUE TITLE
TODO: Fix documentation

### ISSUE THREAD

**Issue by aaronzshey** [Remeic/vue-highlighter#30]
Currently there are no live examples for the code.  This issue is focused on fixing that!
- [x] Basic live example that matches the gif
- [ ] Different hex colors input by the user
- [ ] Different background colors, also input by the user
- [ ] Different paddings, input by the user
- [ ] Examples of the different supported elements (p, ul, ol, button, a)

Current PR: #29
